name: Master
on:
  pull_request:
    branches:
    - master
jobs:
  # Build
  build:
    name: Build
    strategy:
      matrix:
        java-version: [1.8]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install dependencies ${{ matrix.os }}
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update
    # Get Sources
    - name: Checkout sources control
      uses: actions/checkout@v1
    # Setup Environment
    - name: Setup java version $ {{ matrix.java-version }} 
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
        java-package: jdk
        architecture: x64
    # Runner
    - name: Running Environment
      run: |
        java -version
