name: Release
on:
  release:
    types:
    - released
env:
  versions: \${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT
jobs:
  release:
    name: Release
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        java-version: [ 11.0.3 ]
        operating-system: [ ubuntu-latest ]
    steps:
    - name: Prepare
      uses: actions/checkout@v2
    - name: Set Up Java Development Kit
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: adopt
        cache: maven
        server-username: ${{ github.event.repository.owner.login }}
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Prepare Deployment
      run: >-
        mvn
        build-helper:parse-version
        versions:set -DnewVersion=\${{ github.event.release.tag_name }}
        versions:commit
        --no-transfer-progress
    - name: Maven Deploy
      run: >-
        mvn gpg:sign
        --batch-mode
        --no-transfer-progress
        -Dusername=${{ github.event.repository.owner.login }}
        -Dpassword=${{ secrets.GITHUB_TOKEN }}
        deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    - name: Git
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git checkout -b tmp
        mvn build-helper:parse-version versions:set -DnewVersion=${{ env.versions }} versions:commit --no-transfer-progress
        export CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        git add pom.xml
        git commit -m "[SKIP CI] Set ${CURRENT_VERSION}"
        git push origin tmp:develop -f
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
